requires 'perl' => '5.020';
requires 'experimental';
requires 'Cpanel::JSON::XS' => '4.09';
requires 'Crypt::Passphrase' => '0.003';
requires 'Crypt::Passphrase::Bcrypt';
requires 'Digest::MD5';
requires 'Mojolicious' => '7.87';
requires 'Mojo::Log::Role::Clearable';
requires 'Mojo::Pg' => '4.08';
requires 'Spreadsheet::ParseXLSX';
requires 'Syntax::Keyword::Try';
requires 'Text::CSV';
requires 'Text::CSV_XS';
requires 'Text::Unidecode';
requires 'Time::Seconds';
