requires 'perl' => '5.020';
requires 'experimental';
requires 'Crypt::Eksblowfish::Bcrypt';
requires 'Digest::MD5';
requires 'Mojolicious' => '7.31';
requires 'Mojo::Log::Role::Clearable';
requires 'Mojo::JSON::MaybeXS';
requires 'Mojo::Pg' => '4.08';
requires 'Spreadsheet::ParseXLSX';
requires 'Syntax::Keyword::Try';
requires 'Text::CSV';
requires 'Text::CSV_XS';
requires 'Text::Unidecode';
requires 'Time::Seconds';
