requires 'perl' => '5.020';
requires 'experimental';
requires 'Crypt::Eksblowfish::Bcrypt';
requires 'Digest::MD5';
requires 'List::Util' => '1.33';
requires 'Mojolicious' => '7.31';
requires 'Mojo::JSON::MaybeXS';
requires 'Mojo::Pg';
requires 'Text::CSV';
requires 'Text::CSV_XS';
requires 'Text::Unidecode';
requires 'Time::Seconds';
